Import libs

In [2]:
import pandas as pd 
import numpy as np 
import plotly.graph_objects as go
import plotly.express as px
import streamlit as st
from datetime import datetime

load data

In [20]:
def load_data():
 
    """ Loads in 4 dataframes and does light feature engineering"""
    df_agg = pd.read_csv('./data/Aggregated_Metrics_By_Video.csv').iloc[1:,:]
    df_agg.columns = ['Video','Video title','Video publish time','Comments added','Shares','Dislikes','Likes',
                      'Subscribers lost','Subscribers gained','RPM(USD)','CPM(USD)','Average % viewed','Average view duration',
                      'Views','Watch time (hours)','Subscribers','Your estimated revenue (USD)','Impressions','Impressions ctr(%)']
    df_agg['Video publish time'] = pd.to_datetime(df_agg['Video publish time'])
    df_agg['Average view duration'] = df_agg['Average view duration'].apply(lambda x: datetime.strptime(x,'%H:%M:%S'))
    df_agg['Avg_duration_sec'] = df_agg['Average view duration'].apply(lambda x: x.second + x.minute*60 + x.hour*3600)
    df_agg['Engagement_ratio'] =  (df_agg['Comments added'] + df_agg['Shares'] +df_agg['Dislikes'] + df_agg['Likes']) /df_agg.Views
    df_agg['Views / sub gained'] = df_agg['Views'] / df_agg['Subscribers gained']
    df_agg.sort_values('Video publish time', ascending = False, inplace = True)    
    df_agg_sub = pd.read_csv('./data/Aggregated_Metrics_By_Country_And_Subscriber_Status.csv')
    df_comments = pd.read_csv('./data/Aggregated_Metrics_By_Video.csv')
    df_time = pd.read_csv('./data/Video_Performance_Over_Time.csv')
    df_time['Date'] = pd.to_datetime(df_time['Date'])
    return df_agg, df_agg_sub, df_comments, df_time

In [21]:
#create dataframes from the function 
df_agg, df_agg_sub, df_comments, df_time = load_data()

In [22]:
df_agg.head(5)

,Video,Video title,Video publish time,Comments added,Shares,Dislikes,Likes,Subscribers lost,Subscribers gained,RPM(USD),...,Average view duration,Views,Watch time (hours),Subscribers,Your estimated revenue (USD),Impressions,Impressions ctr(%),Avg_duration_sec,Engagement_ratio,Views / sub gained
111,0jTtHYie3CU,Should You Be Excited About Web 3? (As a Data ...,2022-01-17,37,43,8,267,14,18,4.055,...,1900-01-01 00:02:38,4383,192.5779,4,16.549,65130,2.95,158,0.080995,243.500000
187,2RWwN5ZT4tA,Should @Luke Barousse Take This Data Analyst ...,2022-01-14,12,2,3,78,1,1,1.882,...,1900-01-01 00:00:38,2401,25.9375,0,1.720,25094,2.64,38,0.039567,2401.000000
64,rEWPqw6rMGI,The Only Data Science Explanation You Need,2022-01-10,62,141,5,722,28,136,5.971,...,1900-01-01 00:04:40,10277,801.5549,108,60.498,215491,2.22,280,0.090493,75.566176
59,o-wsyxWbPOw,We Need to Talk About The LinkedIn Machine Lea...,2022-01-03,65,36,12,592,10,78,5.321,...,1900-01-01 00:02:46,11808,545.6332,68,62.568,166915,3.32,166,0.059705,151.384615
32,xpIFS6jZbe8,How I Would Learn Data Science in 2022 (If I H...,2021-12-27,109,767,53,4413,46,2553,6.836,...,1900-01-01 00:04:29,79283,5945.5420,2507,528.286,1420968,3.31,269,0.067379,31.054837

,Video,Video title,Video publish time,Comments added,Shares,Dislikes,Likes,Subscribers lost,Subscribers gained,RPM(USD),...,Average view duration,Views,Watch time (hours),Subscribers,Your estimated revenue (USD),Impressions,Impressions ctr(%),Avg_duration_sec,Engagement_ratio,Views / sub gained
111,0jTtHYie3CU,Should You Be Excited About Web 3? (As a Data ...,2022-01-17,37,43,8,267,14,18,4.055,...,1900-01-01 00:02:38,4383,192.5779,4,16.549,65130,2.95,158,0.080995,243.500000
187,2RWwN5ZT4tA,Should @Luke Barousse Take This Data Analyst ...,2022-01-14,12,2,3,78,1,1,1.882,...,1900-01-01 00:00:38,2401,25.9375,0,1.720,25094,2.64,38,0.039567,2401.000000
64,rEWPqw6rMGI,The Only Data Science Explanation You Need,2022-01-10,62,141,5,722,28,136,5.971,...,1900-01-01 00:04:40,10277,801.5549,108,60.498,215491,2.22,280,0.090493,75.566176
59,o-wsyxWbPOw,We Need to Talk About The LinkedIn Machine Lea...,2022-01-03,65,36,12,592,10,78,5.321,...,1900-01-01 00:02:46,11808,545.6332,68,62.568,166915,3.32,166,0.059705,151.384615
32,xpIFS6jZbe8,How I Would Learn Data Science in 2022 (If I H...,2021-12-27,109,767,53,4413,46,2553,6.836,...,1900-01-01 00:04:29,79283,5945.5420,2507,528.286,1420968,3.31,269,0.067379,31.054837

In [5]:
df_agg_sub = pd.read_csv('./data/Aggregated_Metrics_By_Country_And_Subscriber_Status.csv')

In [6]:
df_comments = pd.read_csv('./data/Aggregated_Metrics_By_Video.csv')

In [8]:
df_time = pd.read_csv('./data/Video_Performance_Over_Time.csv')

In [11]:
df_time['Date'] = pd.to_datetime(df_time['Date'])

In [12]:
df_time.head(10)

,Date,Video Title,External Video ID,Video Length,Thumbnail link,Views,Video Likes Added,Video Dislikes Added,Video Likes Removed,User Subscriptions Added,User Subscriptions Removed,Average View Percentage,Average Watch Time,User Comments Added
0,2022-01-19,Kaggle Project From Scratch - Part 2 (Explorat...,KQ80oD_boBM,2191,https://i.ytimg.com/vi/KQ80oD_boBM/hqdefault.jpg,13,0,0,0,0,0,0.069055,151.300154,0
1,2022-01-19,Welcome To My Channel | Ken Jee | Data Science,smeFkHwnM_k,51,https://i.ytimg.com/vi/smeFkHwnM_k/hqdefault.jpg,2,0,0,0,1,0,0.471255,24.034000,0
2,2022-01-19,How She Dominated the FAANG Data Science Inter...,vfV4nm004VQ,2686,https://i.ytimg.com/vi/vfV4nm004VQ/hqdefault.jpg,10,0,0,0,0,0,0.126049,338.567500,0
3,2022-01-19,The 9 Books That Changed My Perspective in 2019,3TrAYmrmA8o,980,https://i.ytimg.com/vi/3TrAYmrmA8o/hqdefault.jpg,1,0,0,0,0,0,0.011508,11.278000,0
4,2022-01-19,Interview with the Director of AI Research @ N...,Xgg7dIKys9E,2904,https://i.ytimg.com/vi/Xgg7dIKys9E/hqdefault.jpg,1,0,0,0,0,0,0.007541,21.900000,0
5,2022-01-19,"Data Science, Machine Learning, and AI: What's...",q8cEt8gj3zY,266,https://i.ytimg.com/vi/q8cEt8gj3zY/hqdefault.jpg,7,0,0,0,0,0,0.584489,155.474143,0
6,2022-01-19,The PODCAST you might have asked for?,tnpV1etgcxs,139,https://i.ytimg.com/vi/tnpV1etgcxs/hqdefault.jpg,1,0,0,0,0,0,0.045813,6.368000,0
7,2022-01-19,#66DaysOfData Round 3 Live Event! (feat. @Stat...,qUK5Vk4NvBw,3735,https://i.ytimg.com/vi/qUK5Vk4NvBw/hqdefault.jpg,2,0,0,0,0,0,0.017095,63.850000,0
8,2022-01-19,5 Proven Strategies to Break into a Data Scien...,UpaEjBOMNqs,334,https://i.ytimg.com/vi/UpaEjBOMNqs/hqdefault.jpg,1,0,0,0,0,0,0.254341,84.950000,0
9,2022-01-19,Reviewing Your Data Science Projects - Episode...,txR8_jGi0Ls,904,https://i.ytimg.com/vi/txR8_jGi0Ls/hqdefault.jpg,4,0,0,0,0,0,0.362091,327.330250,0